-- Data awal HopeAI, dihasilkan dari konten yang sebelumnya tertanam di Pathly.tsx dan Flexa.tsx.
-- Aman dijalankan ulang.

INSERT INTO public.learning_modules (id, sort_order, title, topic, color, position, material_title, material_content, material_summary) VALUES
  (1, 1, 'Pulau Angka', 'Pengenalan Angka 1-10', 'bg-emerald-500', 'center', 'Mengenal Angka Dasar', 'Angka adalah simbol untuk menghitung. 1 (satu) seperti tiang, 2 (dua) seperti bebek, 3 (tiga) seperti burung terbang.', 'Ingat bentuk visual angka untuk mempermudah hafalan.'),
  (2, 2, 'Lembah Penjumlahan', 'Penjumlahan Sederhana', 'bg-blue-500', 'left', 'Konsep Penjumlahan', 'Penjumlahan artinya menggabungkan. Jika kamu punya 1 apel, lalu diberi 1 apel lagi, kamu punya 2 apel. Simbolnya (+).', 'Gabungkan dua kelompok benda menjadi satu.'),
  (3, 3, 'Gua Pengurangan', 'Pengurangan Dasar', 'bg-purple-500', 'right', 'Konsep Pengurangan', 'Pengurangan artinya mengambil sebagian. Ada 5 burung, terbang 2, sisa 3. Simbolnya (-).', 'Hitung mundur atau ambil benda.'),
  (4, 4, 'Puncak Logika', 'Pola & Urutan', 'bg-orange-500', 'center', 'Mengenal Pola', 'Pola adalah urutan yang berulang. Merah, Biru, Merah, Biru... selanjutnya pasti Merah!', 'Perhatikan pengulangan untuk menebak selanjutnya.'),
  (5, 5, 'Hutan Pengetahuan', 'Ilmu Pengetahuan Alam', 'bg-green-600', 'left', 'Makhluk Hidup', 'Makhluk hidup itu bernapas, makan, dan tumbuh. Contohnya manusia, hewan, dan tumbuhan. Batu dan air adalah benda mati.', 'Bedakan antara benda hidup dan benda mati.'),
  (6, 6, 'Kota Bahasa', 'Bahasa & Kata', 'bg-pink-500', 'right', 'Lawan Kata', 'Lawan kata adalah kata yang maknanya berlawanan. Contoh: Besar lawannya Kecil. Panas lawannya Dingin.', 'Belajar antonim untuk memperkaya kosakata.'),
  (7, 7, 'Samudra Geografi', 'Lingkungan Sosial', 'bg-cyan-500', 'center', 'Mengenal Tempat', 'Sekolah adalah tempat belajar. Pasar tempat jual beli. Rumah Sakit tempat berobat.', 'Pahami fungsi tempat-tempat umum di sekitar kita.'),
  (8, 8, 'Benteng Kesehatan', 'Kesehatan Diri', 'bg-red-500', 'left', 'Menjaga Kebersihan', 'Mandi 2 kali sehari. Sikat gigi sesudah makan dan sebelum tidur. Cuci tangan sebelum makan agar bebas kuman.', 'Kebersihan adalah pangkal kesehatan.'),
  (9, 9, 'Galeri Seni', 'Warna & Bentuk', 'bg-yellow-500', 'right', 'Warna Dasar', 'Warna dasar ada Merah, Kuning, Biru. Campuran Merah dan Kuning jadi Oranye. Campuran Biru dan Kuning jadi Hijau.', 'Eksplorasi percampuran warna dan bentuk benda.'),
  (10, 10, 'Puncak Harapan', 'Pengetahuan Umum', 'bg-indigo-600', 'center', 'Rangkuman Pengetahuan', 'Dalam satu minggu ada 7 hari. Dalam satu tahun ada 12 bulan. Bumi itu bulat.', 'Fakta-fakta dasar tentang dunia kita.')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.learning_modules', 'id'), (SELECT max(id) FROM public.learning_modules));

INSERT INTO public.quiz_questions (module_id, sort_order, question, options, answer)
SELECT v.module_id, v.sort_order, v.question, v.options::jsonb, v.answer FROM (VALUES
  (1, 1, 'Angka setelah 2 adalah?', '["1","3","4","5"]', '3'),
  (1, 2, 'Mana yang lebih besar: 5 atau 2?', '["5","2","Sama","0"]', '5'),
  (1, 3, 'Berapa jumlah jari di satu tangan?', '["4","5","6","10"]', '5'),
  (2, 1, '1 + 1 = ?', '["11","2","3","0"]', '2'),
  (2, 2, '2 + 3 = ?', '["5","6","4","1"]', '5'),
  (2, 3, 'Jika Alya punya 2 permen dan Budi memberi 1 lagi, berapa permen Alya?', '["2","3","4","1"]', '3'),
  (3, 1, '5 - 2 = ?', '["3","2","7","5"]', '3'),
  (3, 2, '10 - 5 = ?', '["15","5","0","2"]', '5'),
  (3, 3, 'Ibu membeli 4 telur, pecah 1. Sisa berapa?', '["3","4","5","2"]', '3'),
  (4, 1, '1, 2, 1, 2, ... selanjutnya?', '["1","2","3","0"]', '1'),
  (4, 2, 'A, B, A, B, ... selanjutnya?', '["A","B","C","D"]', 'A'),
  (4, 3, 'Siang, Malam, Siang, ... selanjutnya?', '["Pagi","Malam","Sore","Siang"]', 'Malam'),
  (5, 1, 'Manakah yang merupakan makhluk hidup?', '["Batu","Meja","Kucing","Air"]', 'Kucing'),
  (5, 2, 'Makanan sapi adalah?', '["Daging","Rumput","Nasi","Ikan"]', 'Rumput'),
  (5, 3, 'Matahari terbit di sebelah?', '["Barat","Timur","Utara","Selatan"]', 'Timur'),
  (6, 1, 'Lawan kata dari ''Panas'' adalah?', '["Dingin","Hangat","Api","Terbakar"]', 'Dingin'),
  (6, 2, 'Lawan kata dari ''Besar'' adalah?', '["Raksasa","Kecil","Luas","Tinggi"]', 'Kecil'),
  (6, 3, 'Hewan yang mengeong adalah?', '["Anjing","Ayam","Kucing","Bebek"]', 'Kucing'),
  (7, 1, 'Tempat untuk belajar disebut?', '["Pasar","Sekolah","Bandara","Hotel"]', 'Sekolah'),
  (7, 2, 'Ibu kota negara Indonesia adalah?', '["Bandung","Surabaya","Jakarta","Medan"]', 'Jakarta'),
  (7, 3, 'Lampu lalu lintas warna merah artinya?', '["Jalan","Berhenti","Hati-hati","Ngebut"]', 'Berhenti'),
  (8, 1, 'Kita harus menyikat gigi minimal ... kali sehari.', '["1","2","5","Tidak perlu"]', '2'),
  (8, 2, 'Sebelum makan kita harus?', '["Tidur","Mencuci tangan","Bermain","Lari"]', 'Mencuci tangan'),
  (8, 3, 'Makanan yang sehat mengandung?', '["Banyak gula","Vitamin","Pengawet","Pewarna"]', 'Vitamin'),
  (9, 1, 'Warna langit yang cerah adalah?', '["Hijau","Merah","Biru","Hitam"]', 'Biru'),
  (9, 2, 'Bentuk bola adalah?', '["Kotak","Segitiga","Bulat","Persegi"]', 'Bulat'),
  (9, 3, 'Campuran warna merah dan kuning menghasilkan?', '["Ungu","Hijau","Oranye","Coklat"]', 'Oranye'),
  (10, 1, 'Ada berapa hari dalam satu minggu?', '["5","6","7","10"]', '7'),
  (10, 2, 'Hari setelah Senin adalah?', '["Rabu","Selasa","Minggu","Jumat"]', 'Selasa'),
  (10, 3, 'Apa nama planet tempat kita tinggal?', '["Mars","Bulan","Bumi","Matahari"]', 'Bumi')
) AS v(module_id, sort_order, question, options, answer)
WHERE NOT EXISTS (SELECT 1 FROM public.quiz_questions);

INSERT INTO public.materials (slug, level, sort_order, title, content) VALUES
  ('m1', 'mudah', 1, 'Bab 1: Pengenalan Angka', 'Angka adalah simbol yang digunakan untuk mewakili bilangan. Dalam matematika dasar, kita mengenal angka 0 hingga 9 sebagai digit dasar. Kombinasi digit ini membentuk bilangan yang lebih besar.'),
  ('m2', 'mudah', 2, 'Bab 2: Penjumlahan Sederhana', 'Penjumlahan adalah proses menggabungkan dua kelompok benda atau angka menjadi satu. Tanda tambah (+) digunakan untuk menunjukkan penjumlahan. Misalnya, 2 apel + 1 apel = 3 apel.'),
  ('m3', 'mudah', 3, 'Bab 3: Mengenal Warna Dasar', 'Warna dasar atau primer adalah warna utama yang tidak bisa dibuat dari campuran warna lain. Tiga warna dasar adalah Merah, Kuning, dan Biru. Mencampur warna ini akan menghasilkan warna baru seperti Hijau atau Ungu.'),
  ('m4', 'mudah', 4, 'Bab 4: Mengenal Huruf Vokal', 'Dalam abjad, terdapat huruf vokal dan konsonan. Huruf vokal terdiri dari A, I, U, E, dan O. Huruf-huruf ini sangat penting karena memberikan bunyi pada setiap kata yang kita ucapkan.'),
  ('m5', 'mudah', 5, 'Bab 5: Bagian Tubuh Kita', 'Tubuh manusia terdiri dari berbagai bagian yang memiliki fungsi khusus. Mata untuk melihat, telinga untuk mendengar, hidung untuk mencium bau, dan kulit untuk meraba. Menjaga kebersihan tubuh sangat penting untuk kesehatan.'),
  ('m6', 'mudah', 6, 'Bab 6: Hewan di Sekitar Kita', 'Hewan dapat dibagi menjadi hewan peliharaan dan hewan liar. Kucing dan anjing adalah contoh hewan peliharaan. Singa dan gajah adalah hewan liar. Setiap hewan memiliki cara bergerak yang berbeda, ada yang berjalan, terbang, atau berenang.'),
  ('m7', 'mudah', 7, 'Bab 7: Siang dan Malam', 'Bumi berputar pada porosnya menyebabkan terjadinya siang dan malam. Saat bagian Bumi menghadap Matahari, kita mengalami siang. Saat membelakangi Matahari, kita mengalami malam yang gelap dan bisa melihat Bulan.'),
  ('m8', 'mudah', 8, 'Bab 8: Pentingnya Air', 'Air adalah sumber kehidupan. Manusia, hewan, dan tumbuhan membutuhkan air untuk bertahan hidup. Kita menggunakan air untuk minum, mandi, dan mencuci. Kita harus hemat air dan tidak boleh membuang sampah ke sungai.'),
  ('m9', 'mudah', 9, 'Bab 9: Mengenal Bentuk Geometri', 'Benda-benda di sekitar kita memiliki bentuk. Ada lingkaran seperti bola, persegi seperti jendela, dan segitiga seperti potongan pizza. Mengenal bentuk membantu kita menggambar dan memahami ruang.'),
  ('m10', 'mudah', 10, 'Bab 10: Keluarga Inti', 'Keluarga inti terdiri dari Ayah, Ibu, dan Anak. Setiap anggota keluarga memiliki peran. Kita harus saling menyayangi dan menghormati orang tua serta rukun dengan saudara.'),
  ('m11', 'mudah', 11, 'Bab 11: Arah Mata Angin', 'Untuk mengetahui arah, kita menggunakan mata angin. Empat arah utama adalah Utara, Selatan, Timur (tempat matahari terbit), dan Barat (tempat matahari terbenam).'),
  ('t1', 'menengah', 1, 'Bab 1: Konsep Perkalian', 'Perkalian adalah penjumlahan berulang. Daripada menjumlahkan 3 + 3 + 3 + 3, kita bisa menulisnya sebagai 3 x 4. Hasilnya adalah 12. Ini membantu menghitung jumlah benda dalam kelompok yang sama dengan cepat.'),
  ('t2', 'menengah', 2, 'Bab 2: Siklus Air (Hidrologi)', 'Air di Bumi tidak pernah habis karena siklus air. Air laut menguap menjadi awan (evaporasi), awan menjadi berat dan turun sebagai hujan (presipitasi), lalu air mengalir kembali ke laut. Proses ini terus berulang.'),
  ('t3', 'menengah', 3, 'Bab 3: Sistem Tata Surya', 'Bumi adalah salah satu planet yang mengelilingi Matahari. Ada 8 planet dalam tata surya kita: Merkurius, Venus, Bumi, Mars, Jupiter, Saturnus, Uranus, dan Neptunus. Matahari adalah bintang pusat tata surya.'),
  ('t4', 'menengah', 4, 'Bab 4: Fotosintesis', 'Tumbuhan memasak makanannya sendiri melalui fotosintesis. Dengan bantuan sinar matahari, air, dan karbon dioksida, daun menghasilkan oksigen dan gula. Oksigen inilah yang kita hirup setiap hari.'),
  ('t5', 'menengah', 5, 'Bab 5: Struktur Kalimat (SPOK)', 'Kalimat yang lengkap biasanya memiliki struktur Subjek (pelaku), Predikat (tindakan), Objek (sasaran), dan Keterangan (waktu/tempat). Contoh: ''Ibu (S) memasak (P) nasi (O) di dapur (K)''.'),
  ('t6', 'menengah', 6, 'Bab 6: Sejarah Kemerdekaan', 'Kemerdekaan adalah hak segala bangsa. Mempelajari sejarah para pahlawan yang berjuang melawan penjajah mengajarkan kita tentang keberanian, pengorbanan, dan cinta tanah air.'),
  ('t7', 'menengah', 7, 'Bab 7: Peta dan Globe', 'Peta adalah gambaran permukaan bumi pada bidang datar, sedangkan Globe adalah tiruan bumi berbentuk bulat. Kita belajar tentang benua, samudra, garis khatulistiwa, dan skala jarak melalui peta.'),
  ('t8', 'menengah', 8, 'Bab 8: Energi Terbarukan', 'Energi terbarukan adalah energi yang tidak akan habis, seperti sinar matahari, angin, dan air. Penggunaan energi ini lebih ramah lingkungan dibandingkan bahan bakar fosil seperti minyak bumi dan batu bara.'),
  ('t9', 'menengah', 9, 'Bab 9: Rantai Makanan', 'Di alam, makhluk hidup saling memakan untuk bertahan hidup. Padi dimakan tikus, tikus dimakan ular, ular dimakan elang. Ini disebut rantai makanan. Jika satu hilang, keseimbangan alam akan terganggu.'),
  ('t10', 'menengah', 10, 'Bab 10: Demokrasi dan Pemilu', 'Demokrasi berarti pemerintahan dari rakyat, oleh rakyat, dan untuk rakyat. Salah satu wujudnya adalah Pemilu, di mana warga negara memilih pemimpin mereka secara bebas dan adil.'),
  ('t11', 'menengah', 11, 'Bab 11: Pecahan Sederhana', 'Pecahan mewakili bagian dari keseluruhan. Jika sebuah pizza dipotong menjadi 4 bagian sama besar, satu potong adalah 1/4 (satu per empat). Angka atas disebut pembilang, angka bawah disebut penyebut.'),
  ('s1', 'sulit', 1, 'Bab 1: Aljabar Linear', 'Aljabar linear mempelajari vektor, ruang vektor, transformasi linear, dan sistem persamaan linear. Konsep ini sangat penting dalam fisika modern, grafika komputer, dan pemrosesan data.'),
  ('s2', 'sulit', 2, 'Bab 2: Teori Relativitas', 'Dikemukakan oleh Einstein, teori ini menjelaskan bahwa ruang dan waktu bukanlah hal yang mutlak, melainkan relatif tergantung pada kecepatan pengamat. E=mc² adalah rumus terkenal yang menghubungkan energi dan massa.'),
  ('s3', 'sulit', 3, 'Bab 3: Genetika dan DNA', 'DNA adalah cetak biru kehidupan yang membawa informasi genetik. Genetika mempelajari bagaimana sifat-sifat fisik dan biologis diwariskan dari orang tua ke anak melalui gen dan kromosom.'),
  ('s4', 'sulit', 4, 'Bab 4: Makroekonomi: Inflasi', 'Inflasi adalah penurunan nilai mata uang yang menyebabkan kenaikan harga barang secara umum. Hal ini dipengaruhi oleh jumlah uang beredar, permintaan pasar, dan biaya produksi. Bank sentral mengatur suku bunga untuk mengendalikannya.'),
  ('s5', 'sulit', 5, 'Bab 5: Kecerdasan Buatan (AI)', 'Artificial Intelligence adalah simulasi kecerdasan manusia oleh mesin. Ini mencakup Machine Learning, di mana komputer belajar dari data tanpa diprogram secara eksplisit. AI digunakan dalam pengenalan wajah, mobil otonom, dan asisten digital.'),
  ('s6', 'sulit', 6, 'Bab 6: Perubahan Iklim Global', 'Pemanasan global disebabkan oleh efek rumah kaca akibat emisi karbon berlebih. Dampaknya mencakup mencairnya es kutub, naiknya permukaan laut, dan cuaca ekstrem. Mitigasi dan adaptasi sangat diperlukan.'),
  ('s7', 'sulit', 7, 'Bab 7: Psikologi Kognitif', 'Cabang psikologi ini mempelajari proses mental internal seperti persepsi, memori, pemecahan masalah, dan bahasa. Memahami bagaimana otak memproses informasi membantu dalam pendidikan dan terapi mental.'),
  ('s8', 'sulit', 8, 'Bab 8: Hukum Termodinamika', 'Hukum fisika yang mengatur energi dan panas. Hukum pertama menyatakan energi tidak dapat diciptakan atau dimusnahkan. Hukum kedua menyatakan entropi (ketidakteraturan) dalam sistem tertutup akan selalu meningkat.'),
  ('s9', 'sulit', 9, 'Bab 9: Revolusi Industri 4.0', 'Era industri yang menggabungkan teknologi otomatisasi dengan pertukaran data siber. Ini mencakup Internet of Things (IoT), Cloud Computing, dan Big Data, yang mengubah cara manusia bekerja dan hidup.'),
  ('s10', 'sulit', 10, 'Bab 10: Sastra dan Simbolisme', 'Dalam sastra tingkat lanjut, penulis menggunakan simbolisme untuk menyampaikan makna tersembunyi. Metafora, alegori, dan ironi digunakan untuk mengkritik sosial atau menggambarkan kondisi psikologis karakter secara mendalam.'),
  ('s11', 'sulit', 11, 'Bab 11: Manajemen Strategis', 'Proses perencanaan, pemantauan, analisis, dan penilaian yang dilakukan organisasi untuk mencapai tujuan jangka panjang. Termasuk analisis SWOT (Strengths, Weaknesses, Opportunities, Threats) untuk keunggulan kompetitif.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.sign_items (category, slug, sort_order, title, description, image_url, video_url) VALUES
  ('abjad', 'a', 1, 'Huruf A', 'Kepalkan tangan dengan ibu jari berada di samping jari telunjuk, menghadap ke depan.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/A.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/A.webm'),
  ('abjad', 'b', 2, 'Huruf B', 'Buka telapak tangan lurus ke atas, rapatkan keempat jari, dan tekuk ibu jari ke dalam.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/B.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/B.webm'),
  ('abjad', 'c', 3, 'Huruf C', 'Bentuk tangan melengkung menyerupai huruf C dengan semua jari.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/C.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/C.webm'),
  ('abjad', 'd', 4, 'Huruf D', 'Acungkan jari telunjuk lurus ke atas, jari lainnya membentuk lingkaran.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/D.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/D.webm'),
  ('abjad', 'e', 5, 'Huruf E', 'Tekuk semua jari ke arah telapak tangan.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/E.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/E.webm'),
  ('abjad', 'f', 6, 'Huruf F', 'Tempelkan ujung jari telunjuk ke ibu jari, tiga jari lainnya berdiri tegak.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/F.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/F.webm'),
  ('abjad', 'g', 7, 'Huruf G', 'Kepalkan tangan, acungkan jari telunjuk ke samping.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/G.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/G.webm'),
  ('abjad', 'h', 8, 'Huruf H', 'Acungkan jari telunjuk dan jari tengah lurus ke samping.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/H.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/H.webm'),
  ('abjad', 'i', 9, 'Huruf I', 'Acungkan jari kelingking tegak lurus ke atas.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/I.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/I.webm'),
  ('abjad', 'j', 10, 'Huruf J', 'Gerakkan jari kelingking membentuk pola huruf J.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/J.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/J.webm'),
  ('abjad', 'k', 11, 'Huruf K', 'Acungkan jari telunjuk lurus ke atas dan jari tengah miring ke depan.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/K.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/K.webm'),
  ('abjad', 'l', 12, 'Huruf L', 'Bentuk huruf L dengan jari telunjuk dan ibu jari.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/L.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/L.webm'),
  ('abjad', 'm', 13, 'Huruf M', 'Selipkan ibu jari di bawah jari telunjuk, tengah, dan manis.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/M.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/M.webm'),
  ('abjad', 'n', 14, 'Huruf N', 'Selipkan ibu jari di bawah jari telunjuk dan tengah.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/N.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/N.webm'),
  ('abjad', 'o', 15, 'Huruf O', 'Bentuk lingkaran dengan ujung jari-jari menyatu dengan ibu jari.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/O.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/O.webm'),
  ('abjad', 'p', 16, 'Huruf P', 'Arahkan jari telunjuk ke depan dan jari tengah ke bawah.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/P.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/P.webm'),
  ('abjad', 'q', 17, 'Huruf Q', 'Arahkan jari telunjuk dan ibu jari ke bawah.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/Q.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Q.webm'),
  ('abjad', 'r', 18, 'Huruf R', 'Silangkan jari tengah di atas jari telunjuk.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/R.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/R.webm'),
  ('abjad', 's', 19, 'Huruf S', 'Kepalkan tangan dengan ibu jari menindih jari lainnya.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/S.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/S.webm'),
  ('abjad', 't', 20, 'Huruf T', 'Selipkan ibu jari di antara jari telunjuk dan jari tengah.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/T.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/T.webm'),
  ('abjad', 'u', 21, 'Huruf U', 'Acungkan jari telunjuk dan jari tengah rapat tegak lurus.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/U.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/U.webm'),
  ('abjad', 'v', 22, 'Huruf V', 'Bentuk huruf V dengan jari telunjuk dan jari tengah.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/V.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/V.webm'),
  ('abjad', 'w', 23, 'Huruf W', 'Acungkan tiga jari (telunjuk, tengah, manis) membentuk W.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/W.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/W.webm'),
  ('abjad', 'x', 24, 'Huruf X', 'Bengkokkan jari telunjuk menyerupai kait.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/X.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/X.webm'),
  ('abjad', 'y', 25, 'Huruf Y', 'Acungkan ibu jari dan jari kelingking.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/Y.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Y.webm'),
  ('abjad', 'z', 26, 'Huruf Z', 'Gambar huruf Z di udara menggunakan jari telunjuk.', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/abjad/Z.png', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Z.webm'),
  ('angka', '1', 1, 'Angka 1', 'Acungkan jari telunjuk tangan kanan lurus ke atas.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/1%40InForward.jpg/500px-1%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/01.webm'),
  ('angka', '2', 2, 'Angka 2', 'Acungkan jari telunjuk dan jari tengah membentuk huruf V.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/V%40InForward.jpg/500px-V%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/02.webm'),
  ('angka', '3', 3, 'Angka 3', 'Acungkan ibu jari, telunjuk, dan jari tengah.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/3%40InForward.jpg/500px-3%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/03.webm'),
  ('angka', '4', 4, 'Angka 4', 'Acungkan empat jari dengan ibu jari ditekuk ke dalam.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/4%40InForward.jpg/500px-4%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/04.webm'),
  ('angka', '5', 5, 'Angka 5', 'Buka kelima jari tangan.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/5%40InForward.jpg/500px-5%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/05.webm'),
  ('angka', '6', 6, 'Angka 6', 'Tempelkan jari kelingking dengan ibu jari.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/6%40InForward.jpg/500px-6%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/06.webm'),
  ('angka', '7', 7, 'Angka 7', 'Tempelkan jari manis dengan ibu jari.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/7%40InForward.jpg/500px-7%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/07.webm'),
  ('angka', '8', 8, 'Angka 8', 'Tempelkan jari tengah dengan ibu jari.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/8%40InForward.jpg/500px-8%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/08.webm'),
  ('angka', '9', 9, 'Angka 9', 'Tempelkan jari telunjuk dengan ibu jari.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/9%40InForward.jpg/500px-9%40InForward.jpg', 'http://pmpk.kemdikbud.go.id/sibi/SIBI/angka/09.webm')
ON CONFLICT (category, slug) DO NOTHING;
